# Generated by Django 4.2.11 on 2024-04-14 00:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Episodes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.CharField(max_length=200)),
                ("episode", models.IntegerField()),
                ("title", models.CharField(max_length=200)),
                ("date_on_air", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
                ("transcript", models.TextField()),
            ],
        ),
    ]
